### ISSUE TITLE
Integration not loading after upgrading to 2024.10.0

### ISSUE THREAD

**Issue by kaizersoje** [dummylabs/thewatchman#152]
After upgrading to 2024.10.0, the integration is not loading and getting errors in the log.

```
2024-10-03 20:15:35.694 ERROR (MainThread) [homeassistant.setup] Setup failed for custom integration 'watchman': Unable to import component: cannot import name 'PrettyTable' from 'prettytable' (/usr/local/lib/python3.12/site-packages/prettytable/__init__.py)
File "/config/custom_components/watchman/__init__.py", line 25, in <module>
from .coordinator import WatchmanCoordinator
File "/config/custom_components/watchman/coordinator.py", line 8, in <module>
File "/config/custom_components/watchman/utils.py", line 13, in <module>
File "/config/custom_components/watchman/__init__.py", line 25, in <module>
from .coordinator import WatchmanCoordinator
File "/config/custom_components/watchman/coordinator.py", line 8, in <module>
File "/config/custom_components/watchman/utils.py", line 13, in <module>
```

**Comment by kaizersoje** [comment]
The error resolved itself after upgrading to 2024.10.1
